# Generated by Django 4.2.5 on 2023-09-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('time', models.DateTimeField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[['bajarilmoqda', 'Bajarilmoqda'], ['tugatildi', 'Tugatildi'], ["to'xtadi", "To'xtadi"]], max_length=40)),
            ],
        ),
    ]
